import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import AppProvider from "@/provider/app/AppProvider";
import { usersLink } from "@/lib/links";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accounts = await fetch(usersLink)
  const response = await accounts.json()
  const result = response.data
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
