import { TAccount } from "@/provider/slice/type";

export type ValuesDataType = {
  firstName: string;
  middleName: string;
  lastName: string;
  phone: string;
  email: string;
  dob: string;
  country: string;
  state: string;
  street: string;
  gender: string;
  city: string;
  zipCode: string;
  currency: string;
  occupation: string;
  maritalStatus: string;
  nationality: string;
  accountType: string;
  availableBalance: string;
  currentBalance: string;
  cot: string;
  imf: string;
  authPin: string;
  transferPin: string;
  password: string;
};

export const valuesData: ValuesDataType = {
  firstName: "",
  middleName: "",
  lastName: "",
  phone: "",
  email: "",
  dob: "",
  country: "",
  state: "",
  street: "",
  gender: "",
  city: "",
  zipCode: "",
  currency: "",
  occupation: "",
  maritalStatus: "",
  nationality: "",
  accountType: "",
  availableBalance: "",
  currentBalance: "",
  cot: "",
  imf: "",
  authPin: "",
  transferPin: "",
  password: "",
};

export const countries = [
  "",
  "afghanistan",
  "albania",
  "algeria",
  "andorra",
  "angola",
  "antigua and barbuda",
  "argentina",
  "armenia",
  "australia",
  "austria",
  "azerbaijan",
  "bahamas",
  "bahrain",
  "bangladesh",
  "barbados",
  "belarus",
  "belgium",
  "belize",
  "benin",
  "bhutan",
  "bolivia",
  "bosnia and herzegovina",
  "botswana",
  "brazil",
  "brunei",
  "bulgaria",
  "burkina faso",
  "burundi",
  "cabo verde",
  "cambodia",
  "cameroon",
  "canada",
  "central african republic",
  "chad",
  "chile",
  "china",
  "colombia",
  "comoros",
  "congo (congo-brazzaville)",
  "costa rica",
  "croatia",
  "cuba",
  "cyprus",
  "czechia (czech republic)",
  "democratic republic of the congo",
  "denmark",
  "djibouti",
  "dominica",
  "dominican republic",
  "ecuador",
  "egypt",
  "el salvador",
  "equatorial guinea",
  "eritrea",
  "estonia",
  "eswatini",
  "ethiopia",
  "fiji",
  "finland",
  "france",
  "gabon",
  "gambia",
  "georgia",
  "germany",
  "ghana",
  "greece",
  "grenada",
  "guatemala",
  "guinea",
  "guinea-bissau",
  "guyana",
  "haiti",
  "holy see",
  "honduras",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "israel",
  "italy",
  "jamaica",
  "japan",
  "jordan",
  "kazakhstan",
  "kenya",
  "kiribati",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "latvia",
  "lebanon",
  "lesotho",
  "liberia",
  "libya",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "madagascar",
  "malawi",
  "malaysia",
  "maldives",
  "mali",
  "malta",
  "marshall islands",
  "mauritania",
  "mauritius",
  "mexico",
  "micronesia",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "morocco",
  "mozambique",
  "myanmar (burma)",
  "namibia",
  "nauru",
  "nepal",
  "netherlands",
  "new zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "north korea",
  "north macedonia",
  "norway",
  "oman",
  "pakistan",
  "palau",
  "palestine state",
  "panama",
  "papua new guinea",
  "paraguay",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "qatar",
  "romania",
  "russia",
  "rwanda",
  "saint kitts and nevis",
  "saint lucia",
  "saint vincent and the grenadines",
  "samoa",
  "san marino",
  "sao tome and principe",
  "saudi arabia",
  "senegal",
  "serbia",
  "seychelles",
  "sierra leone",
  "singapore",
  "slovakia",
  "slovenia",
  "solomon islands",
  "somalia",
  "south africa",
  "south korea",
  "south sudan",
  "spain",
  "sri lanka",
  "sudan",
  "suriname",
  "sweden",
  "switzerland",
  "syria",
  "tajikistan",
  "tanzania",
  "thailand",
  "timor-leste",
  "togo",
  "tonga",
  "trinidad and tobago",
  "tunisia",
  "turkey",
  "turkmenistan",
  "tuvalu",
  "uganda",
  "ukraine",
  "united arab emirates",
  "united kingdom",
  "united states of america",
  "uruguay",
  "uzbekistan",
  "vanuatu",
  "vatican city",
  "venezuela",
  "vietnam",
  "yemen",
  "zambia",
  "zimbabwe",
];

export const nationalities = [
  "",
  "afghan",
  "albanian",
  "algerian",
  "american",
  "andorran",
  "angolan",
  "antiguan",
  "argentine",
  "armenian",
  "australian",
  "austrian",
  "azerbaijani",
  "bahamian",
  "bahraini",
  "bangladeshi",
  "barbadian",
  "belarusian",
  "belgian",
  "belizean",
  "beninese",
  "bhutanese",
  "bolivian",
  "bosnian",
  "botswanan",
  "brazilian",
  "british",
  "bruneian",
  "bulgarian",
  "burkinabe",
  "burmese",
  "burundian",
  "cabo verdean",
  "cambodian",
  "cameroonian",
  "canadian",
  "central african",
  "chadian",
  "chilean",
  "chinese",
  "colombian",
  "comorian",
  "congolese (congo-brazzaville)",
  "congolese (congo-kinshasa)",
  "costa rican",
  "croatian",
  "cuban",
  "cypriot",
  "czech",
  "danish",
  "djiboutian",
  "dominican",
  "ecuadorean",
  "egyptian",
  "salvadoran",
  "equatorial guinean",
  "eritrean",
  "estonian",
  "eswatini",
  "ethiopian",
  "fijian",
  "finnish",
  "french",
  "gabonese",
  "gambian",
  "georgian",
  "german",
  "ghanaian",
  "greek",
  "grenadian",
  "guatemalan",
  "guinean",
  "guinea-bissauan",
  "guyanese",
  "haitian",
  "honduran",
  "hungarian",
  "icelandic",
  "indian",
  "indonesian",
  "iranian",
  "iraqi",
  "irish",
  "israeli",
  "italian",
  "ivorian",
  "jamaican",
  "japanese",
  "jordanian",
  "kazakh",
  "kenyan",
  "kiribati",
  "north korean",
  "south korean",
  "kuwaiti",
  "kyrgyz",
  "laotian",
  "latvian",
  "lebanese",
  "lesotho",
  "liberian",
  "libyan",
  "liechtensteiner",
  "lithuanian",
  "luxembourger",
  "madagascan",
  "malawian",
  "malaysian",
  "maldivian",
  "malian",
  "maltese",
  "marshallese",
  "mauritanian",
  "mauritian",
  "mexican",
  "micronesian",
  "moldovan",
  "monacan",
  "mongolian",
  "montenegrin",
  "moroccan",
  "mozambican",
  "namibian",
  "nauruan",
  "nepalese",
  "dutch",
  "new zealander",
  "nicaraguan",
  "nigerien",
  "nigerian",
  "north macedonian",
  "norwegian",
  "omani",
  "pakistani",
  "palauan",
  "palestinian",
  "panamanian",
  "papua new guinean",
  "paraguayan",
  "peruvian",
  "filipino",
  "polish",
  "portuguese",
  "qatari",
  "romanian",
  "russian",
  "rwandan",
  "saint lucian",
  "samoan",
  "san marinese",
  "sao tomean",
  "saudi",
  "scottish",
  "senegalese",
  "serbian",
  "seychellois",
  "sierra leonean",
  "singaporean",
  "slovak",
  "slovenian",
  "solomon islander",
  "somali",
  "south african",
  "spanish",
  "sri lankan",
  "sudanese",
  "surinamese",
  "swazi",
  "swedish",
  "swiss",
  "syrian",
  "taiwanese",
  "tajik",
  "tanzanian",
  "thai",
  "timorese",
  "togolese",
  "tongan",
  "trinidadian",
  "tunisian",
  "turkish",
  "turkmen",
  "tuvaluan",
  "ugandan",
  "ukrainian",
  "uruguayan",
  "uzbek",
  "vanuatuan",
  "venezuelan",
  "vietnamese",
  "welsh",
  "yemeni",
  "zambian",
  "zimbabwean",
];



export const users: TAccount[] = [
  {
    id: "1",
    firstName: "John",
    middleName: "A.",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "1234567890",
    gender: "male",
    dob: "1990-01-01",
    accountNumber: "ACC123456789",
    occupation: "Software Developer",
    currency: "USD",
    nationality: "American",
    maritalStatus: "single",
    street: "123 Elm St",
    city: "Springfield",
    state: "Illinois",
    country: "USA",
    zipCode: "62704",
    availableBalance: 1500.75,
    currentBalance: 1800.5,
    imf: "IMF123",
    cot: "COT123",
    status: "pending",
    accountType: "savings",
    active: true,
    pin: "1234",
    password: "securepassword1",
  },
  {
    id: "2",
    firstName: "Jane",
    middleName: "",
    lastName: "Smith",
    email: "jane.smith@example.com",
    active: true,
    phone: "9876543210",
    gender: "female",
    dob: "1985-05-15",
    accountNumber: "ACC987654321",
    occupation: "Financial Analyst",
    currency: "EUR",
    nationality: "British",
    maritalStatus: "married",
    street: "456 Oak St",
    city: "London",
    state: "Greater London",
    country: "UK",
    zipCode: "WC2N 5DU",
    availableBalance: 2500.0,
    currentBalance: 3000.0,
    imf: "IMF987",
    cot: "COT987",
    status: "success",
    accountType: "checking",
    pin: "5678",
    password: "securepassword2",
  },
  {
    id: "3",
    firstName: "Alex",
    middleName: "B.",
    lastName: "Johnson",
    active: false,
    email: "alex.johnson@example.com",
    phone: "5555555555",
    gender: "other",
    dob: "2000-12-25",
    accountNumber: "ACC555555555",
    occupation: "Student",
    currency: "GBP",
    nationality: "Canadian",
    maritalStatus: "single",
    street: "789 Pine St",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    zipCode: "M5V 2T6",
    availableBalance: 500.0,
    currentBalance: 700.0,
    imf: "IMF555",
    cot: "COT555",
    status: "failed",
    accountType: "student",
    pin: "0000",
    password: "securepassword3",
  },
  {
    id: "4",
    firstName: "Michael",
    middleName: "C.",
    lastName: "Brown",
    email: "michael.brown@example.com",
    phone: "4444444444",
    gender: "male",
    dob: "1980-07-20",
    accountNumber: "ACC444444444",
    active: false,
    occupation: "Engineer",
    currency: "USD",
    nationality: "American",
    maritalStatus: "married",
    street: "101 Maple St",
    city: "Chicago",
    state: "Illinois",
    country: "USA",
    zipCode: "60601",
    availableBalance: 3500.0,
    currentBalance: 4000.0,
    imf: "IMF444",
    cot: "COT444",
    status: "pending",
    accountType: "business",
    pin: "2222",
    password: "securepassword4",
  },
  {
    id: "5",
    firstName: "Emily",
    middleName: "D.",
    lastName: "White",
    email: "emily.white@example.com",
    phone: "3333333333",
    gender: "female",
    active: true,
    dob: "1995-03-12",
    accountNumber: "ACC333333333",
    occupation: "Graphic Designer",
    currency: "EUR",
    nationality: "French",
    maritalStatus: "single",
    street: "202 Birch St",
    city: "Paris",
    state: "Île-de-France",
    country: "France",
    zipCode: "75001",
    availableBalance: 1200.0,
    currentBalance: 1400.0,
    imf: "IMF333",
    cot: "COT333",
    status: "success",
    accountType: "checking",
    pin: "3333",
    password: "securepassword5",
  },
  {
    id: "6",
    firstName: "David",
    middleName: "E.",
    lastName: "Taylor",
    active: true,
    email: "david.taylor@example.com",
    phone: "2222222222",
    gender: "male",
    dob: "1972-11-01",
    accountNumber: "ACC222222222",
    occupation: "Doctor",
    currency: "USD",
    nationality: "American",
    maritalStatus: "married",
    street: "303 Cedar St",
    city: "Austin",
    state: "Texas",
    country: "USA",
    zipCode: "73301",
    availableBalance: 5000.0,
    currentBalance: 5500.0,
    imf: "IMF222",
    cot: "COT222",
    status: "pending",
    accountType: "savings",
    pin: "4444",
    password: "securepassword6",
  },
  {
    id: "7",
    firstName: "Sophia",
    middleName: "F.",
    lastName: "Moore",
    active: false,
    email: "sophia.moore@example.com",
    phone: "1111111111",
    gender: "female",
    dob: "1988-08-15",
    accountNumber: "ACC111111111",
    occupation: "Teacher",
    currency: "GBP",
    nationality: "Australian",
    maritalStatus: "divorced",
    street: "404 Oakwood St",
    city: "Sydney",
    state: "New South Wales",
    country: "Australia",
    zipCode: "2000",
    availableBalance: 800.0,
    currentBalance: 900.0,
    imf: "IMF111",
    cot: "COT111",
    status: "failed",
    accountType: "student",
    pin: "5555",
    password: "securepassword7",
  },
  {
    id: "8",
    firstName: "Oliver",
    middleName: "G.",
    active: false,
    lastName: "King",
    email: "oliver.king@example.com",
    phone: "9999999999",
    gender: "male",
    dob: "1999-02-25",
    accountNumber: "ACC999999999",
    occupation: "Intern",
    currency: "EUR",
    nationality: "German",
    maritalStatus: "single",
    street: "505 Walnut St",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    zipCode: "10115",
    availableBalance: 200.0,
    currentBalance: 300.0,
    imf: "IMF999",
    cot: "COT999",
    status: "success",
    accountType: "student",
    pin: "6666",
    password: "securepassword8",
  },
  {
    id: "9",
    firstName: "Liam",
    middleName: "H.",
    lastName: "Scott",
    email: "liam.scott@example.com",
    phone: "8888888888",
    gender: "male",
    dob: "1965-05-09",
    active: true,
    accountNumber: "ACC888888888",
    occupation: "Entrepreneur",
    currency: "USD",
    nationality: "Canadian",
    maritalStatus: "widowed",
    street: "606 Aspen St",
    city: "Vancouver",
    state: "British Columbia",
    country: "Canada",
    zipCode: "V6B 1H7",
    availableBalance: 10000.0,
    currentBalance: 11000.0,
    imf: "IMF888",
    cot: "COT888",
    status: "success",
    accountType: "business",
    pin: "7777",
    password: "securepassword9",
  },
  {
    id: "10",
    firstName: "Emma",
    active: false,
    middleName: "I.",
    lastName: "Walker",
    email: "emma.walker@example.com",
    phone: "7777777777",
    gender: "female",
    dob: "1978-12-31",
    accountNumber: "ACC777777777",
    occupation: "Lawyer",
    currency: "GBP",
    nationality: "British",
    maritalStatus: "married",
    street: "707 Palm St",
    city: "London",
    state: "Greater London",
    country: "UK",
    zipCode: "EC1A 1BB",
    availableBalance: 7500.0,
    currentBalance: 8000.0,
    imf: "IMF777",
    cot: "COT777",
    status: "pending",
    accountType: "savings",
    pin: "8888",
    password: "securepassword10",
  },
];
