import { TAccount } from "@/provider/slice/type";



export type ValuesDataType = {
  firstName: string;
  middleName: string;
  lastName: string;
  phone: string;
  email: string;
  dob: string;
  country: string;
  state: string;
  street: string;
  gender: string;
  city: string;
  zipCode: string;
  currency: string;
  occupation: string;
  maritalStatus: string;
  nationality: string;
  accountType: string;
  availableBalance: string;
  currentBalance: string;
  cot: string;
  imf: string;
  authPin: string;
  transferPin: string;
  password: string;
};

export const valuesData: ValuesDataType = {
  firstName: "",
  middleName: "",
  lastName: "",
  phone: "",
  email: "",
  dob: "",
  country: "",
  state: "",
  street: "",
  gender: "",
  city: "",
  zipCode: "",
  currency: "",
  occupation: "",
  maritalStatus: "",
  nationality: "",
  accountType: "",
  availableBalance: "",
  currentBalance: "",
  cot: "",
  imf: "",
  authPin: "",
  transferPin: "",
  password: "",
};




export const TransferOutoundInputInitialValues = {
  senderAccountNumber: "",
  recipientAccountName: "",
  recipientAccountNumber: "",
  recipientBankName: "",
  status: "",
  amount: "",
  description: "",
  date: "",
};
export const TransferInboundInputInitialValues = {
  recipientAccountNumber: '',
  senderAccountName: '',
  senderAccountNumber: '',
  senderBankName: '',
  status: '',
  amount: '',
  description: '',
  date: '',
};
export const LoanInputInitialValues = {
  accountNumber: '',
  status: '',
  amount: '',
  reason: '',
  date: '',
};
export const TransactionInputInitialValues = {
  accountNumber: '',
  status: '',
  amount: '',
  description: '',
  date: '',
};

export const LoginInputInitialValues = {
  accountNumber: '',
  password: '',
};














export const countries = [
  "",
  "afghanistan",
  "albania",
  "algeria",
  "andorra",
  "angola",
  "antigua and barbuda",
  "argentina",
  "armenia",
  "australia",
  "austria",
  "azerbaijan",
  "bahamas",
  "bahrain",
  "bangladesh",
  "barbados",
  "belarus",
  "belgium",
  "belize",
  "benin",
  "bhutan",
  "bolivia",
  "bosnia and herzegovina",
  "botswana",
  "brazil",
  "brunei",
  "bulgaria",
  "burkina faso",
  "burundi",
  "cabo verde",
  "cambodia",
  "cameroon",
  "canada",
  "central african republic",
  "chad",
  "chile",
  "china",
  "colombia",
  "comoros",
  "congo (congo-brazzaville)",
  "costa rica",
  "croatia",
  "cuba",
  "cyprus",
  "czechia (czech republic)",
  "democratic republic of the congo",
  "denmark",
  "djibouti",
  "dominica",
  "dominican republic",
  "ecuador",
  "egypt",
  "el salvador",
  "equatorial guinea",
  "eritrea",
  "estonia",
  "eswatini",
  "ethiopia",
  "fiji",
  "finland",
  "france",
  "gabon",
  "gambia",
  "georgia",
  "germany",
  "ghana",
  "greece",
  "grenada",
  "guatemala",
  "guinea",
  "guinea-bissau",
  "guyana",
  "haiti",
  "holy see",
  "honduras",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "israel",
  "italy",
  "jamaica",
  "japan",
  "jordan",
  "kazakhstan",
  "kenya",
  "kiribati",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "latvia",
  "lebanon",
  "lesotho",
  "liberia",
  "libya",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "madagascar",
  "malawi",
  "malaysia",
  "maldives",
  "mali",
  "malta",
  "marshall islands",
  "mauritania",
  "mauritius",
  "mexico",
  "micronesia",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "morocco",
  "mozambique",
  "myanmar (burma)",
  "namibia",
  "nauru",
  "nepal",
  "netherlands",
  "new zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "north korea",
  "north macedonia",
  "norway",
  "oman",
  "pakistan",
  "palau",
  "palestine state",
  "panama",
  "papua new guinea",
  "paraguay",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "qatar",
  "romania",
  "russia",
  "rwanda",
  "saint kitts and nevis",
  "saint lucia",
  "saint vincent and the grenadines",
  "samoa",
  "san marino",
  "sao tome and principe",
  "saudi arabia",
  "senegal",
  "serbia",
  "seychelles",
  "sierra leone",
  "singapore",
  "slovakia",
  "slovenia",
  "solomon islands",
  "somalia",
  "south africa",
  "south korea",
  "south sudan",
  "spain",
  "sri lanka",
  "sudan",
  "suriname",
  "sweden",
  "switzerland",
  "syria",
  "tajikistan",
  "tanzania",
  "thailand",
  "timor-leste",
  "togo",
  "tonga",
  "trinidad and tobago",
  "tunisia",
  "turkey",
  "turkmenistan",
  "tuvalu",
  "uganda",
  "ukraine",
  "united arab emirates",
  "united kingdom",
  "united states of america",
  "uruguay",
  "uzbekistan",
  "vanuatu",
  "vatican city",
  "venezuela",
  "vietnam",
  "yemen",
  "zambia",
  "zimbabwe",
];

export const nationalities = [
  "",
  "afghan",
  "albanian",
  "algerian",
  "american",
  "andorran",
  "angolan",
  "antiguan",
  "argentine",
  "armenian",
  "australian",
  "austrian",
  "azerbaijani",
  "bahamian",
  "bahraini",
  "bangladeshi",
  "barbadian",
  "belarusian",
  "belgian",
  "belizean",
  "beninese",
  "bhutanese",
  "bolivian",
  "bosnian",
  "botswanan",
  "brazilian",
  "british",
  "bruneian",
  "bulgarian",
  "burkinabe",
  "burmese",
  "burundian",
  "cabo verdean",
  "cambodian",
  "cameroonian",
  "canadian",
  "central african",
  "chadian",
  "chilean",
  "chinese",
  "colombian",
  "comorian",
  "congolese (congo-brazzaville)",
  "congolese (congo-kinshasa)",
  "costa rican",
  "croatian",
  "cuban",
  "cypriot",
  "czech",
  "danish",
  "djiboutian",
  "dominican",
  "ecuadorean",
  "egyptian",
  "salvadoran",
  "equatorial guinean",
  "eritrean",
  "estonian",
  "eswatini",
  "ethiopian",
  "fijian",
  "finnish",
  "french",
  "gabonese",
  "gambian",
  "georgian",
  "german",
  "ghanaian",
  "greek",
  "grenadian",
  "guatemalan",
  "guinean",
  "guinea-bissauan",
  "guyanese",
  "haitian",
  "honduran",
  "hungarian",
  "icelandic",
  "indian",
  "indonesian",
  "iranian",
  "iraqi",
  "irish",
  "israeli",
  "italian",
  "ivorian",
  "jamaican",
  "japanese",
  "jordanian",
  "kazakh",
  "kenyan",
  "kiribati",
  "north korean",
  "south korean",
  "kuwaiti",
  "kyrgyz",
  "laotian",
  "latvian",
  "lebanese",
  "lesotho",
  "liberian",
  "libyan",
  "liechtensteiner",
  "lithuanian",
  "luxembourger",
  "madagascan",
  "malawian",
  "malaysian",
  "maldivian",
  "malian",
  "maltese",
  "marshallese",
  "mauritanian",
  "mauritian",
  "mexican",
  "micronesian",
  "moldovan",
  "monacan",
  "mongolian",
  "montenegrin",
  "moroccan",
  "mozambican",
  "namibian",
  "nauruan",
  "nepalese",
  "dutch",
  "new zealander",
  "nicaraguan",
  "nigerien",
  "nigerian",
  "north macedonian",
  "norwegian",
  "omani",
  "pakistani",
  "palauan",
  "palestinian",
  "panamanian",
  "papua new guinean",
  "paraguayan",
  "peruvian",
  "filipino",
  "polish",
  "portuguese",
  "qatari",
  "romanian",
  "russian",
  "rwandan",
  "saint lucian",
  "samoan",
  "san marinese",
  "sao tomean",
  "saudi",
  "scottish",
  "senegalese",
  "serbian",
  "seychellois",
  "sierra leonean",
  "singaporean",
  "slovak",
  "slovenian",
  "solomon islander",
  "somali",
  "south african",
  "spanish",
  "sri lankan",
  "sudanese",
  "surinamese",
  "swazi",
  "swedish",
  "swiss",
  "syrian",
  "taiwanese",
  "tajik",
  "tanzanian",
  "thai",
  "timorese",
  "togolese",
  "tongan",
  "trinidadian",
  "tunisian",
  "turkish",
  "turkmen",
  "tuvaluan",
  "ugandan",
  "ukrainian",
  "uruguayan",
  "uzbek",
  "vanuatuan",
  "venezuelan",
  "vietnamese",
  "welsh",
  "yemeni",
  "zambian",
  "zimbabwean",
];